version: "3.8"

services:
  postgres:
    image: postgres:16
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  typesense:
    image: typesense/typesense:0.25.2
    env_file:
      - ./backend/.env
    environment:
      TYPESENSE_DATA_DIR: /data
      TYPESENSE_CORS_DOMAINS: "*"
    ports:
      - "8108:8108"
    volumes:
      - typesense_data:/data
    command: --data-dir /data --enable-cors

volumes:
  postgres_data:
  typesense_data:
